version: 1
disable_existing_loggers: true

formatters:
  default:
    format: "%(asctime)s [%(threadName)s] [%(levelname)s] %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
# TODO: logs rotation
  # app:
  #   class: logging.handlers.RotatingFileHandler
  #   formatter: default
  #   filename: logs/app.log
  #   maxBytes: 52428800 # 50 Megabytes
  #   backupCount: 9

  # api_rest:
  #   class: logging.handlers.RotatingFileHandler
  #   formatter: default
  #   filename: logs/api-rest.log
  #   maxBytes: 52428800 # 50 Megabytes
  #   backupCount: 9

  # manager_thread:
  #   class: logging.handlers.RotatingFileHandler
  #   formatter: default
  #   filename: logs/manager/thread.log
  #   maxBytes: 52428800 # 50 Megabytes
  #   backupCount: 9


  # interface_thread:
  #   class: logging.handlers.RotatingFileHandler
  #   formatter: default
  #   filename: logs/interface/thread.log
  #   maxBytes: 52428800 # 50 Megabytes
  #   backupCount: 9

root:
  level: WARN
  handlers: [console]

loggers:
  server.app:
    level: INFO
    handlers: [console]
    propagate: no

  server.rest_api:
      level: INFO
      handlers: [console]
      propagate: no

  server.managers.thread_manager:
    level: INFO
    handlers: [console]
    propagate: no

  server.managers.doorbell_manager:
    level: INFO
    handlers: [console]
    propagate: no

  server.interfaces.thread_interface:
    level: INFO
    handlers: [console]
    propagate: no

  server.interfaces.gpio_interface:
    level: INFO
    handlers: [console]
    propagate: no
