API_TITLE: CAMERA SERVER API
API_VERSION: v1

# openapi.json version and URL prefix
OPENAPI_VERSION: 3.0.3
OPENAPI_URL_PREFIX: /

# Enable swagger UI
OPENAPI_SWAGGER_UI_PATH: /docs
OPENAPI_SWAGGER_UI_URL: https://cdn.jsdelivr.net/npm/swagger-ui-dist/

# Thread configuration
THREAD_SERIAL_INTERFACE: /dev/ttyACM0
THREAD_SERIAL_SPEED: 115200
THREAD_UDP_PORT: 45
WIFI_THREAD_COMMANDS: server_camera/server/config/wifi-thread-commands.yml

# Peripherals configuration
PERIPHERALS_DOORBELL_BUTTON: 21
WIFI_CONNECTION_STATUS_POLL_PERIOD_IN_SECS: 1
PERIPHERALS_PRESENCE_DETECTION_PIN: 23

# Video stream config
VIDEO_STREAM_DURATION_IN_SECS: 15
WIFI_ON_TIME_IN_SECS: 20
MAX_WIFI_ON_WAITTING_TIME_IN_SECS: 20

# RPI BOX SERVER CONFIGURATION
RPI_BOX_MAC: E4:5F:01:1E:0A:69
RPI_BOX_PORT: 5000
RPI_BOX_THREAD_PATH: thread/setup

# RPI CLOUD SERVER CONFIGURATION
#RPI_CLOUD_MAC: 08:00:27:12:FB:6B  # VM for tests
RPI_CLOUD_MAC: E4:5F:01:1E:0A:33  # rpi-cloud
RPI_CLOUD_PORTS:
  - 3000
  - 3001
RPI_CLOUD_EVENT_PATH: alarm_event
