API_TITLE: CAMERA SERVER API
API_VERSION: v1

# openapi.json version and URL prefix
OPENAPI_VERSION: 3.0.3
OPENAPI_URL_PREFIX: /

# Enable swagger UI
OPENAPI_SWAGGER_UI_PATH: /docs
OPENAPI_SWAGGER_UI_URL: https://cdn.jsdelivr.net/npm/swagger-ui-dist/

# MQTT CONFIGURATION
#MQTT_BROKER_ADDRESS: 192.168.1.33 #ELECTRICAL PANNEL
MQTT_BROKER_ADDRESS: 192.168.1.16 #RPI cloud
MQTT_USERNAME: rpi_camera
MQTT_PASSWORD: lamp
MQTT_QOS: 1
MQTT_RECONNECTION_TIMEOUT_IN_SEG: 1
MQTT_MAX_RECONNECTION_ATTEMPS: 3
MQTT_MSG_PUBLISH_TIMEOUT_IN_SECS: 5

# Thread configuration
THREAD_SERIAL_INTERFACE: /dev/ttyACM0
THREAD_SERIAL_SPEED: 115200
THREAD_UDP_PORT: 45
THREAD_IPV6_MESH: fe80:0:0:0:bc69:1e17:102c:5655
THREAD_DATSET_KEY: 0e080000000000010000000300000e35060004001fffe002084dbae37e3b1de4ee0708fd742fe48d5a1317051000112233445566778899aabbccddeeff030f4f70656e5468726561642d3465353601024e56041042ea7b8f55878049c237bfaf6cf0ff2b0c0402a0f7f8
THREAD_DEVICE_ID: cam
WIFI_THREAD_COMMANDS: server_camera/server/config/wifi-thread-commands.yml

# Peripherals configuration
PERIPHERALS_DOORBELL_BUTTON: 21
WIFI_CONNECTION_STATUS_POLL_PERIOD_IN_SECS: 1
PERIPHERALS_PRESENCE_DETECTION_PIN: 23
MQTT_ALARM_NOTIFICATION_TOPIC: alarm/notification

# Video stream config
VIDEO_STREAM_DURATION_IN_SECS: 15
WIFI_ON_TIME_IN_SECS: 30
MAX_WIFI_ON_WAITTING_TIME_IN_SECS: 30

# Test connection config
TEST_CONNETION_IP: 192.168.1.1
