WIFI:
  ALL:
    ON: wifi_all-on
    OFF: wifi_all-off
  BANDS:
    2.4GHz:
      ON: wifi_2.4GHz-on
      OFF: wifi_2.4GHz-off
    5GHz:
      ON: wifi_5GHz-on
      OFF: wifi_5GHz-off
    6GHz:
      ON: wifi_6GHz-on
      OFF: wifi_6GHz-off
